Repository matheustirabassi/gg-learning, pull requests merged in 2022-08, with the labels that each got.

#58 Corrige a dependência do pgadmin com o postgres no docker-compose
  backend/docker-compose.yml
Labels: bug

#59 Cria entidade Article e mapeia para o usuário e o artigo
  backend/src/main/kotlin/com/br/gglearning/domain/Article.kt
  backend/src/main/kotlin/com/br/gglearning/domain/User.kt
  backend/src/main/resources/application-prod.properties
Labels: enhancement

#60 Feature/adiciona entidade article
  backend/Procfile
  backend/build.gradle.kts
  backend/src/main/kotlin/com/br/gglearning/domain/Article.kt
  backend/src/main/kotlin/com/br/gglearning/domain/BaseEntity.kt
  backend/src/main/kotlin/com/br/gglearning/domain/User.kt
Labels: documentation

#57 Adiciona paginas
  frontend/package.json
  frontend/public/imgs/python.svg
  frontend/src/App.tsx
  frontend/src/Routes.tsx
  frontend/src/app.scss
  frontend/src/assets/icons/article.svg
  frontend/src/assets/icons/code.svg
  frontend/src/assets/icons/logo.svg
  frontend/src/assets/icons/user.svg
  frontend/src/data/json/articles.json
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/presentation/components/Card/ArticleCard.tsx
  frontend/src/presentation/components/Card/Card.tsx
  frontend/src/presentation/components/Footer/Footer.tsx
  frontend/src/presentation/components/Footer/SideFooter.tsx
  frontend/src/presentation/components/Header/Header.tsx
  frontend/src/presentation/components/PageBaseLayout/PageBaseLayout.tsx
  frontend/src/presentation/components/Question/Question.tsx
  frontend/src/presentation/view/AllArticlesPage/AllArticlesContent.tsx
  frontend/src/presentation/view/AllArticlesPage/AllArticlesView.tsx
  frontend/src/presentation/view/ArticlePage/ArticleContentView.tsx
  frontend/src/presentation/view/ArticlePage/ArticleView.tsx
  frontend/src/presentation/view/HomePage/HomeContentView.tsx
  frontend/src/presentation/view/HomePage/HomeHeaderView.tsx
  frontend/src/presentation/view/HomePage/HomeView.tsx
  frontend/src/presentation/view/QuizzPage/QuizzContentView.tsx
  frontend/src/presentation/view/QuizzPage/QuizzView.tsx
Labels: enhancement

#61 Cria entidade Question e Quizz, e as relaciona
  backend/Procfile
  backend/build.gradle.kts
  backend/src/main/kotlin/com/br/gglearning/domain/Article.kt
  backend/src/main/kotlin/com/br/gglearning/domain/Question.kt
  backend/src/main/kotlin/com/br/gglearning/domain/Quizz.kt
Labels: enhancement

#62 Cria configuração de segurança com spring security
  backend/Procfile
  backend/build.gradle.kts
  backend/src/main/kotlin/com/br/gglearning/config/CustomUserDetails.kt
  backend/src/main/kotlin/com/br/gglearning/config/SecurityConfig.kt
  backend/src/main/kotlin/com/br/gglearning/config/UserPrincipal.kt
  backend/src/main/kotlin/com/br/gglearning/controllers/UserController.kt
  backend/src/main/kotlin/com/br/gglearning/services/UserService.kt
Labels: enhancement, dependencies
